// <auto-generated />
using System;
using DAL.DB;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DAL.Migrations
{
    [DbContext(typeof(ServiceCallDbContext))]
    [Migration("20260210081920_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DAL.Entities.FieldOffice", b =>
                {
                    b.Property<int>("OfficeID")
                        .HasColumnType("int");

                    b.Property<bool>("HasPublicReception")
                        .HasColumnType("bit");

                    b.Property<string>("ReceptionAddress")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("OfficeID");

                    b.ToTable("FieldOffices");
                });

            modelBuilder.Entity("DAL.Entities.ManagementOffice", b =>
                {
                    b.Property<int>("OfficeID")
                        .HasColumnType("int");

                    b.Property<string>("ProfessionalManager")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("OfficeID");

                    b.ToTable("ManagementOffices");
                });

            modelBuilder.Entity("DAL.Entities.Office", b =>
                {
                    b.Property<int>("OfficeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OfficeID"));

                    b.Property<string>("OfficeName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OfficeType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("OfficeID");

                    b.ToTable("Offices");
                });

            modelBuilder.Entity("DAL.Entities.ServiceCall", b =>
                {
                    b.Property<int>("CallID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CallID"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OfficeID")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CallID");

                    b.HasIndex("OfficeID");

                    b.ToTable("ServiceCalls");
                });

            modelBuilder.Entity("DAL.Entities.FieldOffice", b =>
                {
                    b.HasOne("DAL.Entities.Office", "Office")
                        .WithOne("FieldOffice")
                        .HasForeignKey("DAL.Entities.FieldOffice", "OfficeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Office");
                });

            modelBuilder.Entity("DAL.Entities.ManagementOffice", b =>
                {
                    b.HasOne("DAL.Entities.Office", "Office")
                        .WithOne("ManagementOffice")
                        .HasForeignKey("DAL.Entities.ManagementOffice", "OfficeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Office");
                });

            modelBuilder.Entity("DAL.Entities.ServiceCall", b =>
                {
                    b.HasOne("DAL.Entities.Office", "Office")
                        .WithMany("ServiceCalls")
                        .HasForeignKey("OfficeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Office");
                });

            modelBuilder.Entity("DAL.Entities.Office", b =>
                {
                    b.Navigation("FieldOffice");

                    b.Navigation("ManagementOffice");

                    b.Navigation("ServiceCalls");
                });
#pragma warning restore 612, 618
        }
    }
}
